env:
  rgEnvironment: COMPANY-rg-PRODUCT-001
  unitPath: .
  unitProject: '*.csproj'
  appcsConnection: ''
  appcsEnvironmentVariable: AZURE_APP_CONFIGURATION_CONNECTION
  stConnection: ''
  stEnvironmentVariable: AZURE_STORAGE_CONNECTION
jobs:
  build:
    steps:
    - uses: actions/checkout@v2
    - name: use .net 6.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x
    - name: dotnet test
      run: dotnet test ${{ env.unitPath  }}/**/${{ env.unitProject  }}
      env:
        ${{ env.appcsEnvironmentVariable  }}: ${{ env.appcsConnection  }}
        ${{ env.stEnvironmentVariable  }}: ${{ env.stConnection  }}
        ASPNETCORE_ENVIRONMENT: ${{ env.rgEnvironment  }}
        AZURE_FUNCTIONS_ENVIRONMENT: ${{ env.rgEnvironment  }}
                    