trigger:
  batch: true
  branches:
    include:
    - '*'
  paths:
    include:
    - .github/pipelines/community-rg-rachel-infrastructure.yml

pr:
  branches:
    exclude:
    - '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  - template: variables/common.yml
      
stages:
  - stage: development
    condition: ne(variables['Build.SourceBranch'], 'refs/heads/main')
    variables:
      - template: variables/rachel.yml

    jobs:
      - job: deploy_landing_zone
        steps:
          - template: steps/landingzone-infrastructure-steps.yml
            parameters:
              armPath: '$(infrastructurePath)'
              subscriptionId: '$(subscriptionId)'
              subscriptionName: '$(subscriptionName)'
              rgName: '$(rgName)'
              rgLocation: '$(rgLocation)'
              appiName: '$(appiName)'
              kvName: '$(kvName)'
              stName: '$(stName)'
              workName: '$(workName)'

      - job: deploy_appcs_infrastructure
        dependsOn: deploy_landing_zone
        steps:
          - template: steps/appcs-infrastructure-steps.yml
            parameters:
              armPath: '$(infrastructurePath)'
              subscriptionId: '$(subscriptionId)'
              subscriptionName: '$(subscriptionName)'
              rgName: '$(rgName)'
              rgLocation: '$(rgLocation)'
              appcsName: '$(appcsName)'
              appcsSku: '$(appcsSku)'              

      - job: deploy_appcs_settings
        dependsOn: deploy_appcs_infrastructure
        steps:
          - template: steps/appcs-settings-steps.yml
            parameters:
              armPath: '$(infrastructurePath)'
              subscriptionName: '$(subscriptionName)'
              subscriptionId: '$(subscriptionId)'
              rgName: '$(rgName)'
              rgLocation: '$(rgLocation)'
              appcsName: '$(appcsName)'
              appcsKeys: '${{ parameters.appcsKeys }}'
              appcsValues: '${{ parameters.appcsValues }}'

      - job: deploy_sb_infrastructure
        dependsOn: deploy_appcs_settings
        steps:
          - template: steps/sb-infrastructure-steps.yml
            parameters:
              armPath: '$(infrastructurePath)'
              subscriptionId: '$(subscriptionId)'
              subscriptionName: '$(subscriptionName)'
              rgName: '$(rgName)'
              rgLocation: '$(rgLocation)'
              sbName: '$(sbName)'
              sbSku: '$(sbSku)'

      - job: deploy_func_infrastructure
        dependsOn: deploy_appcs_settings
        steps:
          - template: steps/func-infrastructure-steps.yml
            parameters:
              armPath: '$(infrastructurePath)'
              subscriptionId: '$(subscriptionId)'
              subscriptionName: '$(subscriptionName)'
              rgName: '$(rgName)'
              rgLocation: '$(rgLocation)'
              rgEnvironment: '$(rgEnvironment)'
              appiKey: '$(appiKey) '
              appiConnection: '$(appiConnection)'
              funcName: '$(funcName)'
              stName: '$(stName)'
              workName: '$(workName)'

      - job: deploy_webjob_infrastructure
        dependsOn: deploy_appcs_settings
        steps:
          - template: steps/webjob-infrastructure-steps.yml
            parameters:
              armPath: '$(infrastructurePath)'
              subscriptionId: '$(subscriptionId)'
              subscriptionName: '$(subscriptionName)'
              rgName: '$(rgName)'
              rgLocation: '$(rgLocation)'
              rgEnvironment: '$(rgEnvironment)'
              planName: '$(planName)'
              webjobName: '$(webjobName)'

  - stage: production
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
    variables:
      - template: variables/production.yml

    jobs:
      - job: deploy_landing_zone
        steps:
          - template: steps/landingzone-infrastructure-steps.yml
            parameters:
              armPath: '$(infrastructurePath)'
              subscriptionId: '$(subscriptionId)'
              subscriptionName: '$(subscriptionName)'
              rgName: '$(rgName)'
              rgLocation: '$(rgLocation)'
              appiName: '$(appiName)'
              kvName: '$(kvName)'
              stName: '$(stName)'
              workName: '$(workName)'

      - job: deploy_appcs_infrastructure
        dependsOn: deploy_landing_zone
        steps:
          - template: steps/appcs-infrastructure-steps.yml
            parameters:
              armPath: '$(infrastructurePath)'
              subscriptionId: '$(subscriptionId)'
              subscriptionName: '$(subscriptionName)'
              rgName: '$(rgName)'
              rgLocation: '$(rgLocation)'
              appcsName: '$(appcsName)'
              appcsSku: '$(appcsSku)'              

      - job: deploy_appcs_settings
        dependsOn: deploy_appcs_infrastructure
        steps:
          - template: steps/appcs-settings-steps.yml
            parameters:
              armPath: '$(infrastructurePath)'
              subscriptionName: '$(subscriptionName)'
              subscriptionId: '$(subscriptionId)'
              rgName: '$(rgName)'
              rgLocation: '$(rgLocation)'
              appcsName: '$(appcsName)'
              appcsKeys: '${{ parameters.appcsKeys }}'
              appcsValues: '${{ parameters.appcsValues }}'

      - job: deploy_sb_infrastructure
        dependsOn: deploy_appcs_settings
        steps:
          - template: steps/sb-infrastructure-steps.yml
            parameters:
              armPath: '$(infrastructurePath)'
              subscriptionId: '$(subscriptionId)'
              subscriptionName: '$(subscriptionName)'
              rgName: '$(rgName)'
              rgLocation: '$(rgLocation)'
              sbName: '$(sbName)'
              sbSku: '$(sbSku)'

      - job: deploy_func_infrastructure
        dependsOn: deploy_appcs_settings
        steps:
          - template: steps/func-infrastructure-steps.yml
            parameters:
              armPath: '$(infrastructurePath)'
              subscriptionId: '$(subscriptionId)'
              subscriptionName: '$(subscriptionName)'
              rgName: '$(rgName)'
              rgLocation: '$(rgLocation)'
              rgEnvironment: '$(rgEnvironment)'
              appiKey: '$(appiKey) '
              appiConnection: '$(appiConnection)'
              funcName: '$(funcName)'
              stName: '$(stName)'
              workName: '$(workName)'

      - job: deploy_webjob_infrastructure
        dependsOn: deploy_appcs_settings
        steps:
          - template: steps/webjob-infrastructure-steps.yml
            parameters:
              armPath: '$(infrastructurePath)'
              subscriptionId: '$(subscriptionId)'
              subscriptionName: '$(subscriptionName)'
              rgName: '$(rgName)'
              rgLocation: '$(rgLocation)'
              rgEnvironment: '$(rgEnvironment)'
              planName: '$(planName)'
              webjobName: '$(webjobName)'  
