variables:
  - name: subscriptionName
    value: "gtc-sandbox-001"
  - name: artifactsPath
    value: '$(Build.ArtifactStagingDirectory)'
  - name: tempPath
    value: '$(Agent.TempDirectory)/ymltemp'
  - name: archiveFile
    value: 'archive.zip'
  - name: pipelinesPath
    value: '$(System.DefaultWorkingDirectory)/pipelines'
  - name: infrastructurePath
    value: '$(System.DefaultWorkingDirectory)/infrastructure'