variables:
  - group: community-rg-lynda-dev
  - template: common.yml
  - name: rgEnvironment
    value: 'Development'
  - name: rgName
    value: 'rg-lynda-dev-001'
  - name: rgLocation
    value: 'West US 3'
  - name: 'appiName'
    value: 'appi-lynda-dev-001'
  - name: 'kvName'
    value: 'kv-lynda-dev-001'
  - name: 'sqlName'
    value: 'sql-lynda-dev-001'    
  - name: sqlsku
    value: 'F0'
  - name: 'sqldbName'
    value: 'lynda001'
  - name: stName
    value: 'stlyndadev001'
  - name: workName
    value: 'work-lynda-dev-001'