variables:
  - group: community-rg-rachel-dev
  - template: common.yml
  - name: rgEnvironment
    value: 'Development'
  - name: rgName
    value: 'rg-rachel-dev-001'
  - name: rgLocation
    value: 'West US 3'
  - name: 'appiName'
    value: 'appi-rachel-dev-001'
  - name: 'kvName'
    value: 'kv-rachel-dev-001'
  - name: 'sqlName'
    value: 'sql-rachel-dev-001'    
  - name: sqldbSku
    value: 'Basic'
  - name: 'sqldbName'
    value: 'rachel001'
  - name: stName
    value: 'stracheldev001'
  - name: workName
    value: 'work-rachel-dev-001'