variables:
  - group: community-rg-tobi-dev
  - template: common.yml
  - name: rgEnvironment
    value: 'Development'
  - name: rgName
    value: 'rg-tobi-dev-001'
  - name: rgLocation
    value: 'West US 3'
  - name: 'appiName'
    value: 'appi-tobi-dev-001'
  - name: 'kvName'
    value: 'kv-tobi-dev-001'
  - name: 'sqlName'
    value: 'sql-tobi-dev-001'    
  - name: sqlsku
    value: 'F0'
  - name: 'sqldbName'
    value: 'tobi001'
  - name: storageName
    value: 'sttobidev001'
  - name: workName
    value: 'work-tobi-dev-001'